"""Adicionando a tabela de Telefones

Revision ID: 70e5cadd9d9e
Revises: b17bfeef25b8
Create Date: 2019-09-18 15:08:30.095486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e5cadd9d9e'
down_revision = 'b17bfeef25b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_telefone', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefones')
    # ### end Alembic commands ###
