"""Adicionando tabela de endereços

Revision ID: b17bfeef25b8
Revises: cf0d3aebebde
Create Date: 2019-09-18 11:21:06.108653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17bfeef25b8'
down_revision = 'cf0d3aebebde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.Text(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enderecos')
    # ### end Alembic commands ###
