"""Criando as tabelas

Revision ID: fa197683dec1
Revises: 
Create Date: 2019-09-23 13:03:10.589755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa197683dec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('data_nascimento', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.Text(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_telefone', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Text(), nullable=True),
    sa.Column('contato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contato_id'], ['contatos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefones')
    op.drop_table('enderecos')
    op.drop_table('contatos')
    # ### end Alembic commands ###
